### ISSUE TITLE
Why Kotlin

### ISSUE THREAD

**Issue by alexfjw** [nus-cs3281/2018#10]
### Punch 
Java is extremely verbose when compared to other languages. But we don’t have much of a choice due to platform constraints or legacy reasons. There is a solution, and that is Kotlin.

### WILFY
Kotlin makes you a happier developer, by improving clarity, reducing verbosity and bugs. It's like Java, just better. It is likely to take over areas traditionally covered by Java.

### Promise
Kotlin constructs that reduce verbosity & its design philosophy +  where its used & current popularity

### Key Points
1) Kotlin reduces verbosity and encourages good habits
2) Kotlin works seamlessly with ideas from Java & existing Java code, projects
3) Kotlin is emerging & here to stay

### Call to Action
Try Kotlin now!

**Comment by damithc** [comment]
Good key points 👍
