### ISSUE TITLE
Effective, SOLID or Lean Java

### ISSUE THREAD

**Issue by LiHaoTan** [nus-cs3281/2018#12]
## WIIFY
We can almost start immediately improving our code quality just after the talk. That is, if one subscribes to the ideas in the talk.

## Key Points
* Code Quality is difficult, but we can try to focus on a subset.
* We can take Effective Java as an excellent reference point for the subset we focus on.
* Focusing on Java code quality is not sufficient but code quality is hard. However, we can adapt useful related ideas from Effective Java, and probably some of the other Effective series.
* Effective Java is excellent because it prescribes ideas clearly and concisely while taking into account drawbacks.
* However, beyond minimal code quality improvements it is hard to say how much to focus on code quality

## Call to Action
We can take a look at one or more relevant items from Effective Java and start applying. Or start considering why the ideas in the book are not appropriate.

## Slides
[Effective_SOLID_or_Lean_Java.pptx](https://github.com/nus-cs3281/2018/files/1674030/Effective_SOLID_or_Lean_Java.pptx)

**Comment by damithc** [comment]
Assuming we go for a mor focused (and less ambitious) _intended impact_ of getting the audience to read the said book, CtA can be more focused and key points can be more aligned with it. For example,
>1. Writing quality code is hard to learn by trial-and-error
>2. Effective Java is the top book for Java code quality (use reviews/ratings as evidence)
>3. The book has some excellent advise relevant to us (use example as evidence)
> Therefore, read Effective Java to start improving your code quality!
