### ISSUE TITLE
Garbage Collection

### ISSUE THREAD

**Issue by Zhiyuan-Amos** [nus-cs3281/2018#13]
[Slides](https://github.com/nus-cs3281/2018/files/1694584/Lightning.Talk.1.pptx)

WIIFY: Knowing your language's Garbage Collection implementation can help you to resolve bugs such as cyclic dependencies.

Key point: Different languages have different implementations for Garbage Collection, so you have to be aware lest you face some weird bugs.

Call to action: Know your language's Garbage Collection implementation.

**Comment by damithc** [comment]
Key point is well-aligned with the CtA 👍
