### ISSUE TITLE
Go Learn Go

### ISSUE THREAD

**Issue by darrenwee** [nus-cs3281/2018#14]
# Go Learn Go
### Punch
Have you ever wanted the expressiveness and be as easy to learn as Python but hold the performance and low level control of compiled languages like C or C++?

### WILFY
Learning Go opens many employment opportunities for you, and gives you a more versatile and easy-to-acquire tool to add to your kit.

### Promise
(some) technical merits of Go, and its current presence in industry

### Key Points
1. Go has good language design - safe, expressive and easy to learn.
2. Go is designed to take advantage of modern architecture.
3. Go is emerging as a highly demanded technology.

### Call to Action
Go learn Go!

# [slides here](https://docs.google.com/presentation/d/1gjksgaZ2RK6crbZvGWQLnlCu1PcDBox_IibqsZS6VmI/edit?usp=sharing)

## Go Examples
During Q&A, Dat requested for some examples. Unfortunately I did not include them in the slides, but I will put them here instead.

#### Multiple Returns
```go
package main

import "fmt"

// The `(int, int)` in this function signature shows that
// the function returns 2 `int`s.
func vals() (int, int) {
    return 3, 7
}

func main() {

    // Here we use the 2 different return values from the
    // call with _multiple assignment_.
    a, b := vals()
    fmt.Println(a) // prints 3
    fmt.Println(b) // prints 7

    // If you only want a subset of the returned values,
    // use the blank identifier `_`.
    _, c := vals()
    fmt.Println(c) // prints 7
}
```
[run example here](https://play.golang.org/p/chwFmr5dG1)

#### Error Handling without Exceptions
```go
package main

import (
	"fmt"
	"math"
)

type ErrorNegativeSqrt float64 // declare a new type

// implement a function for the type 'error'
func (e ErrorNegativeSqrt) Error() string {
	return fmt.Sprintf("cannot Sqrt negative number: %f", e)
}

func Sqrt(x float64) (float64, error) {
	if x < 0 {
		return -1.0, ErrorNegativeSqrt(x)
	}
	// no issues with sqrt-ing, so nil error
	return math.Sqrt(x), nil
}

func main() {
	fmt.Println(Sqrt(2))
	fmt.Println(Sqrt(-2))
}

```

[run example here](https://play.golang.org/p/Z26-ujYCeOb)

#### Simple Concurrency Example
This program sums all the elements in an array by breaking it down into 2 sub-tasks to sum each half of the array, each run in a goroutine. The answer for each sub-task is then used to compute the sum of the array.
```go
package main

import "fmt"

func sum(s []int, c chan int) {
	sum := 0
	for _, v := range s {
		sum += v
	}
	c <- sum // send sum to c
}

func main() {
	s := []int{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15}
	c := make(chan int)

	go sum(s[:len(s)/2], c) // launch a goroutine to sum each half!
	go sum(s[len(s)/2:], c)

	x, y := <-c, <-c // receive from c

	fmt.Printf("Goroutine 1: sum = %d\n", x)
	fmt.Printf("Goroutine 2: sum = %d\n", y)
	fmt.Printf("Total sum = %d\n", x+y)

}
```
[run example here](https://play.golang.org/p/uy16aHaAXwY)

**Comment by damithc** [comment]
Keypoints are nicely aligned with call to action 👍
