### ISSUE TITLE
Typography: The Visual Language

### ISSUE THREAD

**Issue by junkiattan** [nus-cs3281/2018#15]
### Content
1. Definition of typography and its importance
2. Difference between typography and content
3. Factors that affect typography
4. Tips on applying typography to content

### Slides
[Typography_The Visual Language_Lightning Talks A.pptx](https://github.com/nus-cs3281/2018/files/1672527/Typography_The.Visual.Language_Lightning.Talks.A.pptx)

### WIIFY
Readers only read an average of 20% of content, so learning typography helps to maximize overall reader engagement with the content to convey intended message and impression

### Key points
- Typography is responsible for users' first impression in a project and users generally read only an average of 20% of the posted content, hence it's importance in capturing and retaining user attention
- Achieving above point is not just about content, since typography (how it's said) and content (what is said) are two different things and hence must be considered separately
- Specifically on typography, there are two factors that affect how typography is used: Readers (target audience) and Type of Message
- Though different, both content and typography can complement each other to communicate effectively, whose success is determined by both Legibility (specific design elements) and Readability (how design affect user engagement). 

### Call to action
In order to improve the quality of content, don't just count your words, _use typography_ to make them count!

**Comment by damithc** [comment]
Try to make the keypoints lead up to the call to action e.g.,
> 1. Typography is important as it's responsible for users' first impression
> 2. ?
> 3. ?
>
>Therefore, start paying more attention to typography in your work!

The key points you have are all important/useful points, but they don't fit together to lead up to a single call to action, which dilutes the focus of the talk.
