### ISSUE TITLE
Speed up Python the C++ way

### ISSUE THREAD

**Issue by bqnguyen94** [nus-cs3281/2018#16]
[Slides](https://github.com/nus-cs3281/2018/files/1674008/Steroid.Python.the.C.way.pptx)

**WIIFY**: Speed up your Python code up to 100 times faster today!

**Key points**:

* It is important to speed up Python
  * Python is a popular language (because of its flexible syntax and dynamic typing)
  * Python is widely used in every field: AI, data science, web dev, game dev, etc.
  * Python is slow, resource-intensive

* Why used C++ to speed up Python
   * C++ is much faster (allow memory management)
   * Some 3rd party library for C++ is more powerful (OpenCV CUDA module only has C++ interface)

* How to port a function to C++ and use in Python
   * Write the C++ version of the function
   * Write helper function to transform Python args to C++ data type
   * Wrap the package using `disutil`
   * Import and call the function in Python

**Call to action**: WRITE YOUR PYTHON C++ API RIGHT NOW!!!

**Comment by bqnguyen94** [comment]
Slides: [Steroid Python the C++ way.pptx](https://github.com/nus-cs3281/2018/files/1673596/Steroid.Python.the.C.way.pptx)

**Comment by bqnguyen94** [comment]
**WIIFY**: Speed up your Python code up to 100 times faster today!

**Key points**:

* What is Python
   * A scripting language aims at flexibility, dynamicality, and versatility
   * Easy to pick up with not so strict syntax, handle things like memory management, dynamic type
   * Widely used and various fields with thousands of 3rd party libraries

* Why combine Python and C++
   * Python is slow, resources intensive
   * C++ is much faster (allow memory management), and some 3rd party library for C++ is more powerful (OpenCV CUDA module only has C++ interface)

* How to port a function to C++ and use in Python
   * Write the C++ version of the function
   * Write helper function to transform Python args to C++ data type
   * Wrap the package using `disutil`
   * Import and call the function in Python

**Call to action**: WRITE YOUR PYTHON C++ API RIGHT NOW!!!

**Comment by damithc** [comment]
1. Update the issue description (the first comment) rather than add as new comments.
2. `What is Python` is a topic, not a point.

**Comment by damithc** [comment]
Keypoints are not necessarily the talk summary, nor the talk roadmap. It can be something like this:
>* Python is easy to use but can be slow at times
>* C++ is fast but not easy to use
>* With a little bit of work, you can get C++ performance in python programs, by ...
>
>Therefore, start using C++ in your Python code now!
