### ISSUE TITLE
Natural Language Processing: Why Should You Care?

### ISSUE THREAD

**Issue by craaaa** [nus-cs3281/2018#17]
### PUNCH
I missed out on buying $10 bitcoin because I didn't know why or how to jump on the Bitcoin hype train. I don't want you to miss out on the $10 bitcoin of the AI world: NLP.

### WIIFY
If you miss the NLP train, you'll sorely regret it!

### Key points
- NLP may seem technical and distant from the software developing world
- NLP is used everywhere: NLP is used in human-used programs
- NLP builds usable software: it makes software that users will find natural to use
- NLP is usable: there are many libraries available for you to easily integrate NLP into your work

### Call to action
Jump on the NLP train!

**Comment by damithc** [comment]
Good key points; the first point does not align with the Call to Action though.
