### ISSUE TITLE
Bash: Speed Up and Automate Your Workflow

### ISSUE THREAD

**Issue by vivekscl** [nus-cs3281/2018#19]
## WIIFY 
Become much more efficient as a software developer by learning **just the basics** of Bash.

## Content
* What is Bash?
* How to speed up your workflow with Bash
* Bash vs other scripting languages

## Key Points
* Easy to pick up and apply on the go
* Just learning the basics of Bash pays off 
* Know when and how to use Bash

## Call To Action
Get up to speed with Bash and start bashing away at your projects to see your efficiency grow to new heights.

## Slides

[Bash_ Speed Up And Automate Your Workflow.pptx](https://github.com/nus-cs3281/2018/files/1673277/Bash_.Speed.Up.And.Automate.Your.Workflow.pptx)

**Comment by damithc** [comment]
Good key points, but the third one doesn't seem to fit the flow (as you can see from the following text):
>1. Bash is easy to pick up and apply on the go
>2. Just learning the basics of Bash pays off
>3. Know when and how to use Bash
> Therefore, start using Bash to automate your work!

Something like this flows better:
>1. Bash is easy to pick up and apply on the go
>2. Just learning the basics of Bash pays off
>3. Bash can automate tasks like {...} better than full-fledged languages like Python
> Therefore, start using Bash to automate your work!
