### ISSUE TITLE
Linting JavaScript with ESLint

### ISSUE THREAD

**Issue by nicholaschuayunzhi** [nus-cs3281/2018#20]
# Punch
Example of the frustration caused when submitting PRs for code review without a linter.

# WIIFY

## General
* Widely used in many popular Javascript open source repositories
  * Good for submitting PR for external project
* A better experience when submitting pull request
  * Saves time
  * Prevents embarassment

## For javascript beginners
* Helps check your code for errors or potential bugs
* Easy to set-up and start coding

# Keypoints
* ESLint helps to:
  * Identify Possible errors
  * Check for Style Errors
  * Enforce Best Practices

# Call to Action
Use ESLint in your next Javascript project!

# Slides
Slides available [here](https://docs.google.com/presentation/d/1Qxi6-V8idBdJUW3ZOyGrPuTmDl1sNMTgsNbbuVmSzpE/edit?usp=sharing)

**Comment by damithc** [comment]
@nicholaschuayunzhi update the description as required and let me know

**Comment by nicholaschuayunzhi** [comment]
@damithc Sorry prof. I've updated the description.

**Comment by damithc** [comment]
Good key points.
