### ISSUE TITLE
Why Choose Vue

### ISSUE THREAD

**Issue by LuLechuan** [nus-cs3281/2018#21]
**Link to the slides**
[lightning_talk_1.pptx](https://github.com/nus-cs3281/2018/files/1703153/lightning_talk_1.pptx)

**PUNCH**
The story of me trying to build a JavaScript front-end function. After going through asking people a few rounds, discovering that self-learning is the best.

**WIFFY**
VueJs can help you to know how to develop JavaScript front-end easily. It is really worthy and easy to learn.

**Keypoints**
VueJs is a JavaScript framework
VueJs is approachable - easy to learn
VueJs is versatile
VueJs can make codes short and clean

**Call to Action**
Learn VueJs

**Comment by damithc** [comment]
Need to update the descrption. See schedule page for details.
Let me know after updating.

**Comment by LuLechuan** [comment]
@damithc Hi Prof, the issue is updated. Sorry for missing the todo. I will be punctual next time.

**Comment by damithc** [comment]
> What is VueJs?
> It is a JavaScript framework that designed to segregate web applications into orthogonal units to improve code quality and maintainability.
> 
> What is the advantages of Vue.js over other JavaScript framework?
> (a) VueJs is easy to learn
> (b) VueJs is versatile and allow you to develop many functions
> (c) VueJs can make codes short and clean
> 
> How to use Vue.js?
> This is done through live demonstration

This is more like the roadmap of the talk, not necessarily the key points. Key points can be as follows:

> * VueJs is a JavaScript framework
> * VueJs is easy to learn
> * VueJs is versatile 
> * VueJs can make codes short and clean
> Therefore, use Vue.

**Comment by LuLechuan** [comment]
Changes made as requested.
