### ISSUE TITLE
Boost C++ libraries

### ISSUE THREAD

**Issue by yamidark** [nus-cs3281/2018#24]
[Slides](https://github.com/nus-cs3281/2018/files/1695582/CS3281_2_Lightning_Talk_01.pptx)

**WIIFY**
Boost C++ can help improve productivity for our C++ projects.

**Key Points**
- Boost has a collection of high-quality modern libraries that complement C++ standard
- One example, Boost.Flyweight can help us in memory optimization easily
- Boost gives us a head start on new technology faster than the standard library

**Call to action**
Get and start exploring Boost C++ to boost your C++ code and projects.

**Comment by damithc** [comment]
Keypoints are generally aligned with the intended impact. Perhaps the example should not be considered a keypoint (rather, it is a supporting evidence for a key point).

>* Boost reduces development effort
>* Boost is high quality
>* Boost is future proof
>Therefore, start using Boost!
