### ISSUE TITLE
Java Streams: why it can be good to go with the flow

### ISSUE THREAD

**Issue by joanneong** [nus-cs3281/2018#25]
**Link to slides**
[Java Streams (CS3281).pptx](https://github.com/nus-cs3281/2018/files/1672758/Java.Streams.CS3281.pptx)

**PUNCH**
Many people hate Java. Programmers even complain about getting repetitive strain injury from coding Java.

**WIIFY**
Java streams can help you to become a better Java programmer, which is good since Java is set to remain popular at least in the near future

**Promise**
Crash/refresher course on Streams: what are Streams? How to use Streams? Why use Streams?

**Key points**
1. What are Streams?
a) A stream is a sequence of elements that supports operations on its elements. 

2. How to use Streams?
a) There are many ways to create a stream source from a data source.
b) Intermediate stream operations
&nbsp;&nbsp;&nbsp; i) Intermediate stream operations can be chained together to form an operation pipeline.
&nbsp;&nbsp;&nbsp; ii) Intermediate stream operations are always lazy.
c) Terminal stream operations
&nbsp;&nbsp;&nbsp; i) Side effects: Terminal stream operations can produce side effects.
&nbsp;&nbsp;&nbsp; ii) Results: Terminal stream operations can produce results.

3. Why use Streams?
a) Streams make for more readable and maintainable code
b) Streams make for less verbose code
c) Streams allow for performance improvement through parallelism (parallel streams)

**Call to action**
Explore the Java streams library today, and try out streams

**Comment by damithc** [comment]
Key points are not necessarily the talk summary, nor the talk roadmap. For me, the key points (which leads directly to the call to action) of your talk are as follows:
> 1. Streams can make the code shorter
> 2. Streams can make the code simpler
> 3. Streams can make the code faster
> Therefore, [call to action = use streams in your Java code!]

Whereas the talk roadmap can be:
>1. What are streams?
>2. How to use them?
>3. Why they are good?
