### ISSUE TITLE
Safeguard your code from memory leaks

### ISSUE THREAD

**Issue by Zhiyuan-Amos** [nus-cs3281/2018#31]
Topic: Safeguard your code from memory leaks

PUNCH - Story about a bug in AB-Level4:
1. Test passes on Travis & AppVeyor, but fails locally.
2. Test passes when the failing test is executed on its own.

WIIFY: Don't spend your weekends debugging time-consuming memory leaks bugs.

Points:
1. Prevent memory leaks by using logging.
2. Prevent memory leaks by not using static objects.

Call to action: Use logging & don't use static objects to safeguard your code from memory leaks.
[Lightning Talk 2.pptx](https://github.com/nus-cs3281/2018/files/1802071/Lightning.Talk.2.pptx)

**Comment by damithc** [comment]
Comments added in the GoogleDoc
