### ISSUE TITLE
Git Better

### ISSUE THREAD

**Issue by darrenwee** [nus-cs3281/2018#32]
# [slides](https://docs.google.com/presentation/d/1AfaGl0dH07_RorYnQec2wuvIQieMQdzwum6TiNL75i0/edit?usp=sharing)
## Punch
I first started using git in a team a year and a half ago in CS2103 and was constantly confused by what was the right thing to do. Should I merge or rebase? What am I supposed to write for a commit message? Why are there so many conflicts? I spent more time trying to fix my git problems than I did coding.

I’m sure many of us have had a similar experience at the start, or even today still have some leftover bad habits like me or aren’t sure what to do.

## WILFY
You will become a more productive developer and master the skills for collaboration.

## Roadmap
1. how to be a better collaborator using best practices,
2. an example of how to be more productive using git.

## Key Points
1. Following best practices makes you a better document-er and collaborator
2. You need best practices to use advanced git tools to enhance productivity

## Promise
Learn about some best practices of git and a useful tool: `git bisect`

## Call to Action
Git better at git!

**Comment by damithc** [comment]
Comments added in the GoogleDoc
