### ISSUE TITLE
Static Analysis Tools

### ISSUE THREAD

**Issue by tshradheya** [nus-cs3281/2018#34]
# Topic
Static Analysis Tools

# PUMA

## Punch
Google code had lots of bugs which were only discovered once static analysis using FindBugs tool was done

## WIIFY

Using Static Analysis tools can make your code perfect and help reviewers and developers for easy maintainability of code

## Key Points

- Static Analysis Tools are necessary for developers
- Use these tools in the right way to improve efficiency
- These tools are highly beneficial for all kinds of software

## Call to Action/Impact

Start using Static Analysis Tools in all projects extensively in order to write production quality code and develop perfect Software

# Slides 
[LT2 Slides.pptx](https://github.com/nus-cs3281/2018/files/1802750/LT2.Slides.pptx)

**Comment by damithc** [comment]
Comments added in the GoogleDoc
