### ISSUE TITLE
Web Scraping

### ISSUE THREAD

**Issue by danielbrzn** [nus-cs3281/2018#38]
PUNCH: Sometimes APIs are unavailable/crippled for the websites that you intend to build a platform on top of.

WIIFY: Learn how web scraping can benefit you today

Roadmap: 
1) Define web scraping
2) Benefits
3) Live demo
4) QnA

Key Points:

1) Web scraping allows you to rely on yourself (instead of the website) to get the data that you need. No waiting is required for an official API to be opened up.

2) It is possible to be anonymous when you scrape, unlike APIs. APIs require you to authenticate your requests with a key provided the server, and as such, the website administrators will know who is making the requests. Whereas for scraping, requests can be done behind a proxy to mask your identity.

Call to Action: Unshackle yourself from APIs by using web scraping today

[WebScrapingFinal.pptx](https://github.com/nus-cs3281/2018/files/1784304/WebScrapingFinal.pptx)

**Comment by damithc** [comment]
Key points?

**Comment by danielbrzn** [comment]
Updated.
