### ISSUE TITLE
Why use Node.js

### ISSUE THREAD

**Issue by rachx** [nus-cs3281/2018#42]
### PUNCH:
NASA uses node.js to help keep their astronauts safe as they found that it works well, fast and is inexpensive. Node.js is probably useful for you as well.

### WIIFY:
Learn about a new runtime environment to write better and faster server-side apps

### Roadmap:
* What is Node.js
* When to use Node.js
* Other benefits

### Key Points
* Node is fast
* Node has great support
* Node makes development easier - same language for front-end and back-end.

### Call to Action:
Check out some Node resources. Consider using Node to make your next project better!

### Slides:
[Nodejs.pptx](https://github.com/nus-cs3281/2018/files/1802176/Nodejs.pptx)

**Comment by damithc** [comment]
Comments added in the GoogleDoc
