### ISSUE TITLE
Basic Memory Safety ideas in Rust

### ISSUE THREAD

**Issue by LiHaoTan** [nus-cs3281/2018#47]
## WIIFY
Learn how to use memory safety ideas to improve memory and resource management.

## Key Points
* Memory management is not a solved problem
* Memory safety ideas in Rust fills in the gaps
* Memory safety ideas are not exclusive to Rust

## Call to Action
Use the memory safety ideas employed in Rust to improve memory and resource management in your program!

## Slides
[Basic Memory Safety ideas in Rust.pptx](https://github.com/nus-cs3281/2018/files/1784719/Basic.Memory.Safety.ideas.in.Rust.pptx)

## Additional notes

Memory management is closely related to resource management, and automatic resource management in languages with GCs is not really a solved problem. Rust employs some ideas for resource safety which thereby also includes memory safety.

The ideas for resource safety in Rust are not new ([see RAII](https://stackoverflow.com/questions/2321511/what-is-meant-by-resource-acquisition-is-initialization-raii)). However, Rust expands upon it through the concept of ownership and borrowing, which helps one reason about resource management and [concurrency](https://blog.rust-lang.org/2015/04/10/Fearless-Concurrency.html).

The [concept of ownership](https://codewithoutrules.com/2017/01/26/object-ownership/) is also not exclusive to Rust and can be useful in other languages.

**Comment by OngInAWell** [comment]
test

**Comment by OngInAWell** [comment]
### GIGO #13
