### ISSUE TITLE
Java Reflection

### ISSUE THREAD

**Issue by yamidark** [nus-cs3281/2018#51]
**WIIFY**
Java Reflection allows us to inspect and modify program structure during runtime.

**Key Points**
- Reflection allows us to access and modify private fields and methods.
- Reflection is useful when working with 3rd party libraries which we can't modify.
- Reflections is useful when working on code that is dynamically changing during runtime.

**Call to action**
Start exploring the Java Reflection API so that we can do alot more with our program.

[Slides](https://github.com/nus-cs3281/2018/files/1802688/CS3281_2_Lightning_Talk_02.pptx)

**Comment by damithc** [comment]
Comments added in the GoogleDoc
