### ISSUE TITLE
async/await in JavaScript

### ISSUE THREAD

**Issue by nicholaschuayunzhi** [nus-cs3281/2018#53]
# WIIFY
async/await makes writing asynchronous code easier

# Key Points
async/await makes writing asynchronous code
- clean and concise
- easy to write
- easier to debug

# Call To Action
Let's use async await to make writing asynchronous code easier

Slides: [Async Await.pptx](https://github.com/nus-cs3281/2018/files/1823949/Async.Await.pptx)

**Comment by damithc** [comment]
Comments added to GoogleDoc
