### ISSUE TITLE
Protocol Oriented Programming in Swift

### ISSUE THREAD

**Issue by rachx** [nus-cs3281/2018#6]
## WIIFY
Learn an alternative and cleaner way to design your app in popular and productive languages - Swift and Kotlin (which both support POP well)

## Key Points

- Protocols work with value types which has no implicit sharing of data and their associated problems.
- Protocol extensions with default implementation can prevent code duplication.
- Protocol composition gives us more flexibility. Choose the requirements you need without creating a god class or complex architecture.

## Call To Action
Start with the requirements (a protocol) instead of a class to create clean designs.
Consider learning Swift to take advantage of value types and protocols

Slides: [POP.pptx](https://github.com/nus-cs3281/2018/files/1695393/POP.pptx)

**Comment by damithc** [comment]
A strongly focused call to action? e.g.,

>* POP can fix some OOP problems
>* POP can reduce code duplication
>* POP gives more flexibility
>Therefore, switch to a languge that supports POP!
