### ISSUE TITLE
Promises in JavaScript

### ISSUE THREAD

**Issue by danielbrzn** [nus-cs3281/2018#7]
WIIFY: Master promises and be able to use asynchronous Javascript code with ease
Key Points:

- Promises to allow asynchronous methods to "return" a value just like synchronous methods
- Promises bring certainty to your code so that it is easier to debug
- Promises allow chaining multiple asynchronous methods together to ensure their sequential execution
- Promises ensure that your functions are not deeply nested, unlike callbacks

Therefore, start using Promises in your Javascript code today!

[Promises.pptx](https://github.com/nus-cs3281/2018/files/1672770/Promises.pptx)
#

**Comment by damithc** [comment]
Can rephrase the keypoints to make them more aligned with the call to action.
>* Promises allow asynchronous methods to "return" a value just like synchronous methods
>* Promises bring certainty to your code so that it is easier to debug
>* ...
>* ...
>
>Therefore, start using Promises in your JS code!
