### ISSUE TITLE
Cross-site request forgery (CSRF)

### ISSUE THREAD

**Issue by tran-tien-dat** [nus-cs3281/2018#9]
Link to the slides: [CSRF Presentation.pdf](https://github.com/nus-cs3281/2018/files/1673112/CSRF.Presentation.pdf)

# PUNCH
Did you know that the simple HTML form that you learn from online tutorial is vulnerable to CSRF, an attack that could allow attackers to perform any actions on a web service, such as transfering money out of bank accounts?

# WIIFY
Understanding CSRF and the defense against it is vital for all web application!

# Key Points
- Web authentication is implemented using a secret cookie identifying the user that is sent along every request to your website.
- CSRF can happen because
  - Other website can also trigger requests to your website and these requests also contain the secret cookie
  - Your server does not verify that the request actually comes from your website
- To defend against CSRF, we should add a pseudo-random token associated with the user to every forms that change data on your website.

# Call to Action
Protect your website against CSRF and use an anti-CSRF token.

**Comment by damithc** [comment]
Keypoints can be more aligned with the call to action. e.g.,
>1. CSRF can happen to any website
>2. CSRF can cause serious damage
>3. There are some easy ways to avoid CSRF
>
> Therefore, use CSFR protection in your web applications!
